# allow debugbar to show up when using webpack server
when@dev:
    nelmio_cors:
        defaults:
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
